import assert from "node:assert/strict";
import fs from "node:fs";
const read=(p)=>fs.readFileSync(new URL(`../${p}`,import.meta.url),"utf8");
const records=JSON.parse(read("data/articles.json"));
const board=read("components/trending-board.tsx");
const page=read("app/page.tsx");
const header=read("components/header.tsx");
const css=read("app/globals.css");
assert.ok(records.length>=20,"records available for trending rows");
assert.ok(records.every(a=>a.sourceUrl.startsWith("https://")&&/^\d{4}-\d{2}-\d{2}$/.test(a.publishedAt)&&/^\d{4}-\d{2}-\d{2}$/.test(a.checkedAt)));
assert.ok(board.includes('const WINDOWS =')&&["今日","本周","本月","近一年","全部时间"].every(w=>board.includes(w)));
assert.ok(["搜索关键词","按行业筛选","按时间筛选","排序方式","原始资料"].every(w=>board.includes(w)));
assert.ok(board.includes('按公开资料的发布日期排序')&&board.includes('非流量热度榜')&&board.includes('并非实时抓取'));
assert.ok(board.includes('dateInWindow(a,window.days)')&&board.includes('a.publishedAt.localeCompare')&&board.includes('safe')===false);
assert.ok(page.includes('TrendingBoard')&&header.includes('Trending 趋势')&&css.includes('.trend-row'));
const snapshot=records.map(a=>a.checkedAt).sort().at(-1);
assert.ok(snapshot);
const ms=date=>Date.parse(`${date}T00:00:00Z`);
const count=days=>records.filter(a=>{const diff=ms(snapshot)-ms(a.publishedAt);return diff>=0&&diff<days*86400000}).length;
assert.ok(count(1)<=count(7)&&count(7)<=count(30)&&count(30)<=records.length);
assert.ok(count(7)>0&&count(30)>0,"current snapshot has articles in recent ranges");
console.log(`PASS: Trending UI structure, transparent ranking, filters, ${records.length} source-linked entries; snapshot ${snapshot}, day/week/month = ${count(1)}/${count(7)}/${count(30)}.`);
