import type { Metadata } from "next";
import Link from "next/link";
import { Building2, CalendarDays, ExternalLink, Search } from "lucide-react";
import { projects } from "@/data/projects";
import { safeUrl } from "@/lib/format";
export const metadata: Metadata = { title: "电子制造项目台账", description: "依据官方公告整理印度 PCB、覆铜板、连接器、光收发器项目获批主体及原始证据。" };
const sectors=["全部","PCB / PCBA","服务器与电子制造"];
export default async function Projects({searchParams}:{searchParams:Promise<{q?:string;sector?:string}>}){
 const p=await searchParams;
 const sector=sectors.includes(p.sector??"")?p.sector!:"全部";
 const q=(p.q??"").trim().slice(0,80).toLowerCase();
 const visible=projects.filter(project=>(sector==="全部"||project.sector===sector)&&(!q||`${project.name} ${project.product} ${project.sector} ${project.state}`.toLowerCase().includes(q)));
 return <div className="container-page py-12 sm:py-16"><div className="eyebrow">PROJECT WATCH / 项目追踪</div><h1 className="mt-3 text-3xl font-black text-navy sm:text-4xl">电子制造项目台账</h1><p className="mt-4 max-w-4xl text-sm leading-8 text-[#647884]">从政府公布的投资与产业项目中提取公司、产品、批准日期及原始链接。这里只记录可核对的项目状态，不对任何公司进行信用评分或违法推断。</p><div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 px-5 py-4 text-sm leading-7 text-amber-900"><strong>状态说明：</strong>所有台账项目仅确认“官方公布获批”，不是已投产、已获得稳定良率或能够交付特定订单的保证；不同项目的具体工艺范围必须另行核实。</div><form action="/projects" className="panel mt-8 flex items-center gap-3 p-3"><Search className="shrink-0 text-[#71848b]" size={18}/><input className="min-w-0 flex-1 bg-transparent p-2 text-sm outline-none" name="q" aria-label="检索项目" placeholder="检索公司、PCB、覆铜板、SFP…" defaultValue={p.q??""} maxLength={80}/><input type="hidden" name="sector" value={sector==="全部"?"":sector}/><button className="primary-btn" type="submit">搜索</button></form><div className="mt-5 flex flex-wrap gap-2">{sectors.map(s=><Link key={s} href={`/projects${s==="全部"?"":`?sector=${encodeURIComponent(s)}`}`} className={`rounded-full border px-4 py-2 text-xs font-bold ${s===sector?"border-brand bg-brand text-white":"border-[#dce8e4] bg-white text-[#66777d]"}`}>{s}</Link>)}</div><p className="mt-6 text-xs text-[#758993]">当前显示 {visible.length} / {projects.length} 项 · 数据复核日：2026-09-24</p><div className="mt-4 grid gap-4 md:grid-cols-2">{visible.map(item=><article key={item.id} className="panel p-6"><div className="flex flex-wrap items-center gap-2"><span className="tag">{item.sector}</span><span className="rounded-full bg-[#fff4db] px-2.5 py-1 text-xs font-semibold text-[#926116]">{item.stage}</span></div><h2 className="mt-4 flex gap-2 text-lg font-extrabold leading-7 text-navy"><Building2 size={18} className="mt-1 shrink-0 text-brand"/>{item.name}</h2><p className="mt-3 text-sm leading-7 text-[#4b626e]"><strong>涉及产品：</strong>{item.product}</p><p className="mt-2 flex items-center gap-1 text-xs text-[#829199]"><CalendarDays size={13}/>公告日期 {item.approvedOn} · 地区：{item.state}</p><p className="mt-4 border-t border-[#ecf1ef] pt-4 text-xs leading-6 text-[#687c84]">{item.note}</p><a href={safeUrl(item.sourceUrl)} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-brand">查看官方项目公告<ExternalLink size={14}/></a></article>)}</div>{visible.length===0&&<div className="panel mt-4 p-12 text-center text-sm text-[#758993]">暂无匹配项目，请修改检索条件。</div>}<p className="mt-8 text-xs leading-6 text-[#788a93]">如需追加公司信息，请提供公开披露链接并通过<Link href="/submit" className="font-bold text-brand">事实更正入口</Link>反馈。未经核对的用户叙述不自动进入官方项目台账。</p></div>;
}
