import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowLeft,ExternalLink} from 'lucide-react';
import {dossiers,findDossier} from '@/data/dossiers';
import {safeUrl} from '@/lib/format';
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return dossiers.map(d=>({slug:d.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const d=findDossier((await params).slug);return {title:d?.title??'专题不存在',description:d?.subtitle};}
export default async function DossierPage({params}:Props){const d=findDossier((await params).slug);if(!d)notFound();return <div className="container-page max-w-[1000px] py-12 sm:py-16"><Link href="/dossiers" className="inline-flex items-center gap-2 text-sm font-bold text-brand"><ArrowLeft size={16}/>返回专题研究</Link><div className="eyebrow mt-8">RESEARCH DOSSIER / 专题研究</div><h1 className="mt-4 text-3xl font-black leading-snug text-navy sm:text-4xl">{d.title}</h1><p className="mt-5 max-w-3xl text-sm leading-8 text-[#607780]">{d.subtitle}</p><p className="mt-5 text-xs text-[#80939a]">最后复核：{d.updatedAt} · 公开资料分析，非针对单一企业的法律或投资建议</p><div className="mt-8 space-y-6">{d.sections.map((s,i)=><section className="panel p-6 sm:p-9" key={s.heading}><p className="eyebrow">SECTION {String(i+1).padStart(2,'0')}</p><h2 className="mt-3 text-xl font-extrabold leading-8 text-navy">{s.heading}</h2>{s.body.map(t=><p className="mt-4 text-sm leading-8 text-[#586d79]" key={t}>{t}</p>)}{s.questions&&<div className="mt-6 rounded-xl bg-[#eef7f2] p-5"><h3 className="text-sm font-extrabold text-[#1a7064]">企业尽调时应回答</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-7 text-[#516e66]">{s.questions.map(q=><li key={q}>{q}</li>)}</ul></div>}</section>)}</div><section className="panel mt-6 p-6 sm:p-9"><h2 className="text-xl font-extrabold text-navy">原始来源与查证</h2><p className="mt-3 text-sm leading-7 text-[#6a7b85]">下列链接均为可追溯的监管、政府或企业公开资料，阅读时应注意原文时间及后续更新。</p><div className="mt-5 space-y-3">{d.sources.map(src=><a className="flex gap-2 break-words text-sm font-semibold leading-7 text-brand hover:underline" key={src.url} href={safeUrl(src.url)} target="_blank" rel="noopener noreferrer"><ExternalLink className="mt-1 shrink-0" size={15}/>{src.label}</a>)}</div></section></div>}
