"use client";
import {useState,type FormEvent} from "react";
import Script from "next/script";
import Link from "next/link";
import {CheckCircle2,AlertCircle,LockKeyhole} from "lucide-react";
import {reportCategories} from "@/lib/config";
export function SubmissionForm({enabled,siteKey}:{enabled:boolean;siteKey:string}){
 const [status,setStatus]=useState<"idle"|"submitting"|"success"|"error">("idle");const [message,setMessage]=useState("");const [kind,setKind]=useState("EXPERIENCE");
 async function onSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!enabled)return;const form=e.currentTarget;const values=new FormData(form);const token=String(values.get("cf-turnstile-response")??"");if(!token){setStatus("error");setMessage("请先完成人机验证。");return;}setStatus("submitting");
 const body={kind:values.get("kind"),category:values.get("category"),title:values.get("title"),body:values.get("body"),sourceUrl:values.get("sourceUrl"),contactEmail:values.get("contactEmail"),consent:values.get("consent")==="on",turnstileToken:token,homepage:values.get("homepage")};
 try{const response=await fetch("/api/submissions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.message??"无法提交，请稍后重试");setStatus("success");setMessage("提交已收到并进入非公开审核队列；并非已通过审核或已公开发布。");form.reset();}catch(error){setStatus("error");setMessage(error instanceof Error?error.message:"网络错误，请重试");}
 }
 return <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_280px]"><div className="panel p-6 sm:p-8">{!enabled&&<div className="mb-6 flex items-start gap-2 rounded-xl border border-[#e8d8b8] bg-[#fff9e9] p-4 text-sm leading-7 text-[#846326]"><AlertCircle size={18} className="mt-1 shrink-0"/>投稿尚未开放：站点维护方需要先配置数据库、审核员账户、验证码和公开联系邮箱；本页面仅展示流程，不会保存表单内容。</div>}{status==="success"?<div role="status" className="py-16 text-center"><CheckCircle2 size={44} className="mx-auto text-brand"/><h2 className="mt-5 text-xl font-bold">投稿已提交</h2><p className="mx-auto mt-3 max-w-md text-sm leading-8 text-[#71818a]">{message}</p><button onClick={()=>{setStatus("idle");setMessage("");}} className="outline-btn mt-6">提交另一条经验</button></div>:<form onSubmit={onSubmit} className="space-y-6"><div><label className="mb-2 block text-sm font-bold">投稿类型 <span className="text-red-600">*</span></label><div className="grid grid-cols-2 gap-3"><label className={`cursor-pointer rounded-xl border p-4 text-sm font-bold ${kind==="EXPERIENCE"?"border-brand bg-soft text-brand":"border-[#e0e9e6]"}`}><input type="radio" name="kind" className="mr-2" value="EXPERIENCE" checked={kind==="EXPERIENCE"} onChange={()=>setKind("EXPERIENCE")}/>分享经历</label><label className={`cursor-pointer rounded-xl border p-4 text-sm font-bold ${kind==="CORRECTION"?"border-brand bg-soft text-brand":"border-[#e0e9e6]"}`}><input type="radio" name="kind" className="mr-2" value="CORRECTION" checked={kind==="CORRECTION"} onChange={()=>setKind("CORRECTION")}/>更正与回应</label></div></div>
<div><label htmlFor="category" className="mb-2 block text-sm font-bold">领域分类 *</label><select className="field" id="category" name="category" required>{reportCategories.map(c=><option key={c} value={c}>{c}</option>)}</select></div>
<div><label htmlFor="title" className="mb-2 block text-sm font-bold">标题 *</label><input id="title" name="title" className="field" minLength={8} maxLength={140} required placeholder="简述时间、合作环节及遇到的问题"/></div>
<div><label htmlFor="body" className="mb-2 block text-sm font-bold">事实经过 / 更正理由 *</label><textarea id="body" name="body" rows={8} className="field resize-y" minLength={100} maxLength={6000} required placeholder="请说明大致日期、交易或项目类型、协议约定、实际发生的情况和当前处理状态。更正请注明需要更正的公开内容和依据。不要粘贴合同原件、私人信息、技术秘密或涉密材料。"/><p className="mt-2 text-xs text-[#819099]">至少 100 字，最多 6,000 字。请仅写你有权披露的事实。</p></div>
<div><label htmlFor="sourceUrl" className="mb-2 block text-sm font-bold">相关公开来源（选填）</label><input className="field" id="sourceUrl" name="sourceUrl" type="url" maxLength={1500} placeholder="https:// 公告、新闻或公开处理文书链接"/><p className="mt-2 text-xs leading-6 text-[#819099]">仅提供已公开、可合法分享的网址；不接受私有云盘、含个人信息或保密技术资料的链接。</p></div>
<div><label htmlFor="contactEmail" className="mb-2 block text-sm font-bold">联系邮箱 *</label><input className="field" id="contactEmail" name="contactEmail" type="email" maxLength={254} required autoComplete="email" placeholder="仅供必要核实，不公开展示"/></div>
<div className="hidden" aria-hidden="true"><label htmlFor="homepage">主页（不要填写）</label><input id="homepage" tabIndex={-1} name="homepage" autoComplete="off"/></div>
<label className="flex cursor-pointer items-start gap-3 text-xs leading-6 text-[#607781]"><input type="checkbox" name="consent" required className="mt-1 h-4 w-4 accent-brand"/><span>我确认提交的内容不包含我无权披露的商业秘密、个人信息或其他敏感信息，同意平台为审核与核实目的处理本次投稿和联系邮箱。我已阅读<Link href="/about" className="font-bold text-brand underline">审核与隐私规则</Link>。</span></label>
{enabled&&<><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js" strategy="afterInteractive"/><div className="cf-turnstile" data-sitekey={siteKey}/></>}
{status==="error"&&<div role="alert" className="rounded-xl bg-[#fff3f0] p-3 text-sm text-[#ad4b3a]">{message}</div>}
<button className="primary-btn w-full" disabled={!enabled||status==="submitting"} type="submit">{status==="submitting"?"正在提交…":"提交至人工审核"}</button></form>}</div>
<aside className="space-y-4"><div className="panel p-6"><div className="flex items-center gap-2 font-bold text-navy"><LockKeyhole size={18} className="text-brand"/>提交前请确认</div><p className="mt-3 text-xs leading-7 text-[#6e8089]">切勿上传或直接粘贴公司保密文件、未公开工艺、个人身份信息、涉密国家安全信息。公开案例由编辑另行整理，联系邮箱不公开。</p></div><div className="panel p-6"><h3 className="font-bold text-navy">审核流程</h3><div className="mt-4 space-y-3 text-xs leading-6 text-[#70828a]"><div>01 · 私密接收投稿</div><div>02 · 核查来源、隐私与内容边界</div><div>03 · 必要时要求补充公开材料</div><div>04 · 编辑决定公开、匿名化、退回或拒绝</div><div>05 · 相关方可以申请更正与回应</div></div></div></aside></div>
}
