import type {Metadata} from "next";
import Link from "next/link";
import {Search,SlidersHorizontal} from "lucide-react";
import {articles} from "@/data/articles";
import {categories} from "@/lib/config";
import {ArticleCard} from "@/components/article-card";
export const metadata:Metadata={title:"产业情报库",description:"印度 PCB、电子制造、半导体与跨境合规公开资料索引。"};
export default async function Insights({searchParams}:{searchParams:Promise<{category?:string;q?:string}>}){
 const p=await searchParams;const selected=categories.includes(p.category as typeof categories[number])?p.category:"全部";const q=(p.q??"").slice(0,70).trim();const results=articles.filter(a=>(selected==="全部"||a.category===selected)&&(!q||`${a.title} ${a.excerpt} ${a.takeaway} ${a.points.join(" ")} ${a.tags.join(" ")} ${a.sourceLabel}`.toLowerCase().includes(q.toLowerCase())));
 return <div className="container-page py-12 sm:py-16"><div className="eyebrow">RESEARCH / INDUSTRY INTELLIGENCE</div><h1 className="mt-3 text-3xl font-black text-navy sm:text-4xl">产业情报库</h1><p className="mt-4 max-w-3xl text-sm leading-8 text-[#687a84]">印度产业政策、制造项目、贸易措施与中国企业跨境业务相关信息。分别标注事件时间、来源发布日期、核验日期与编辑解读；获批不等于投产。</p><form action="/insights" className="panel mt-8 flex items-center gap-3 px-4 py-2"><Search size={18} className="shrink-0 text-[#728a8c]"/><input name="q" defaultValue={q} placeholder="检索 PCB、半导体、ECMS、投资规定…" maxLength={70} className="min-w-0 flex-1 bg-transparent py-2 text-sm outline-none" aria-label="搜索情报"/><input type="hidden" name="category" value={selected==="全部"?"":selected}/><button className="primary-btn px-5 py-2" type="submit">搜索</button></form><div className="mt-7 flex flex-wrap items-center gap-2"><SlidersHorizontal size={15} className="mr-1 text-[#73898c]"/>{["全部",...categories].map(c=><Link key={c} href={`/insights${c==="全部"?"":`?category=${encodeURIComponent(c)}`}`} className={`rounded-full border px-3.5 py-2 text-xs font-semibold ${selected===c?"border-brand bg-brand text-white":"border-[#dbe7e3] bg-white text-[#60757d] hover:border-brand hover:text-brand"}`}>{c}</Link>)}</div><div className="mt-7 flex items-center justify-between"><span className="text-xs text-[#819098]">共 {results.length} 条公开情报</span><span className="text-xs text-[#819098]">按事件日期排序</span></div>{results.length?<div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{results.map(a=><ArticleCard article={a} key={a.slug}/>)}</div>:<div className="panel mt-4 p-12 text-center text-sm text-[#7d8d94]">没有匹配的资料。请调整关键词或分类。</div>}</div>
}
