import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowLeft,ExternalLink,CalendarDays,Info,ShieldCheck} from "lucide-react";
import {articles,findArticle} from "@/data/articles";
import {safeUrl} from "@/lib/format";
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const a=findArticle((await params).slug);return {title:a?.title??"未找到资料",description:a?.excerpt,alternates:a?{canonical:`/insights/${a.slug}`}:undefined};}
export default async function InsightDetail({params}:Props){const a=findArticle((await params).slug);if(!a)notFound();return <div className="container-page max-w-[1020px] py-12 sm:py-16"><Link href="/insights" className="inline-flex items-center gap-2 text-sm font-bold text-brand"><ArrowLeft size={16}/>返回情报库</Link><div className="mt-8 flex flex-wrap items-center gap-2"><span className="tag">{a.category}</span><span className="tag">{a.kind}</span></div><h1 className="mt-5 max-w-4xl text-3xl font-black leading-[1.45] text-navy sm:text-4xl">{a.title}</h1><div className="mt-5 flex flex-wrap items-center gap-4 text-xs text-[#74858d]"><span className="flex items-center gap-1"><CalendarDays size={14}/>{a.date} · 事件/生效日</span><span>原始来源：{a.sourceLabel}</span><span>资料发布时间：{a.publishedAt}</span><span>最后核验：{a.checkedAt}</span></div><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_270px]"><article className="panel article-body p-6 sm:p-9"><p className="!mt-0 text-base font-semibold text-[#415965]">{a.excerpt}</p><h2 className="mt-8 border-l-4 border-brand pl-3 text-xl font-extrabold text-navy">原始资料要点</h2><ul className="mt-4 list-disc pl-5 text-sm text-[#506674]">{a.points.map(p=><li key={p}>{p}</li>)}</ul><div className="mt-9 rounded-xl border border-[#cbe2d8] bg-soft p-5"><h3 className="flex items-center gap-2 text-base font-bold text-[#146e62]"><ShieldCheck size={18}/>对企业的参考价值</h3><p className="!mt-2 text-sm leading-8 text-[#436d67]">{a.takeaway}</p></div><div className="mt-6 rounded-xl border border-[#dfe9e5] bg-[#f8fbfa] p-4 text-xs leading-7 text-[#63777f]"><strong>证据类别：</strong>{a.sourceType} · {a.verification}</div><div className="mt-4 flex flex-wrap gap-2">{a.tags.map(t=><span key={t} className="tag">{t}</span>)}</div><h2 className="mt-9 text-lg font-bold text-navy">原始资料</h2><p className="text-sm text-[#697e86]">建议在做出投资或交易决策前，直接核对原文及其后续修订、调查公告或实施细则。</p><a className="mt-5 inline-flex items-center gap-2 rounded-xl border border-[#c9dcd5] bg-white px-4 py-3 text-sm font-bold text-brand hover:border-brand" href={safeUrl(a.sourceUrl)} target="_blank" rel="noopener noreferrer">{a.sourceLabel}<ExternalLink size={16}/></a><p className="break-all text-xs text-[#8a9aa0]">{a.sourceUrl}</p></article><aside className="space-y-4"><div className="panel p-5"><span className="eyebrow">SOURCE POLICY</span><h2 className="mt-2 text-sm font-bold text-navy">信息标注规则</h2><p className="mt-3 text-xs leading-7 text-[#73838c]">本条内容基于注明的公开来源编写。官方计划、获批投资、实际建设及商业化结果是不同状态，不能相互替代。</p></div><div className="panel p-5"><div className="flex items-start gap-2"><Info size={17} className="mt-0.5 shrink-0 text-brand"/><p className="text-xs leading-7 text-[#6b8189]">发现日期、数字或原始来源有误？可通过投稿页面提交事实更正。</p></div><Link href="/submit" className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-brand">提交更正 →</Link></div></aside></div></div>}
