import type {Metadata} from "next";
import Link from "next/link";
import {ArrowUpRight,CalendarDays,MessageSquareText} from "lucide-react";
import {db} from "@/lib/db";
import {safeUrl} from "@/lib/format";
export const dynamic="force-dynamic";
export const metadata:Metadata={title:"企业经验与回应",description:"仅展示人工审核且经编辑确认可以公开的跨境合作经验与相关回应。"};
export default async function Submissions(){
 let reports: {id:string,kind:"EXPERIENCE"|"CORRECTION",category:string,publicTitle:string|null,publicBody:string|null,editorNote:string|null,publishedAt:Date|null,sourceUrl:string|null}[]=[];
 if(process.env.DATABASE_URL){try{reports=await db().report.findMany({where:{status:"PUBLISHED",publicTitle:{not:null},publicBody:{not:null}},select:{id:true,kind:true,category:true,publicTitle:true,publicBody:true,editorNote:true,publishedAt:true,sourceUrl:true},orderBy:{publishedAt:"desc"},take:40});}catch(e){console.error("Unable to load public submissions",e);}}
 return <div className="container-page py-12 sm:py-16"><div className="eyebrow">EXPERIENCE / INDUSTRY COMMUNITY</div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="mt-3 text-3xl font-black text-navy sm:text-4xl">企业经验与回应</h1><p className="mt-4 max-w-3xl text-sm leading-8 text-[#687a84]">只展示经过编辑审核、适合公开的经验及回应。个人经历不等于法院或监管机构已确认的事实。</p></div><Link href="/submit" className="primary-btn">分享经验<ArrowUpRight size={16}/></Link></div><div className="mt-8 rounded-xl border border-[#b8d9ce] bg-[#edf8f2] p-4 text-sm leading-7 text-[#3a6c62]">投稿默认不公开；编辑审核将重点关注证据、匿名化、权利人回应和个人信息保护。平台不按国籍建立企业信用排名。</div>{reports.length===0?<div className="panel mt-7 flex flex-col items-center px-5 py-20 text-center"><MessageSquareText size={32} className="text-brand"/><h2 className="mt-4 text-xl font-bold text-navy">公开经验库正在建设中</h2><p className="mt-3 max-w-md text-sm leading-7 text-[#788994]">目前没有已经审核并公开的用户投稿。平台不会把模拟案例伪装成真实投诉，欢迎提交可核查的交易经历与公开资料。</p><Link href="/insights" className="outline-btn mt-6">先浏览产业情报</Link></div>:<div className="mt-7 grid gap-5 md:grid-cols-2">{reports.map(r=><article className="panel p-6" key={r.id}><div className="flex items-center gap-2"><span className="tag">{r.kind==="CORRECTION"?"回应与更正":"当事人经验"}</span><span className="text-xs text-[#80929a]">{r.category}</span></div><h2 className="mt-4 text-lg font-extrabold leading-7 text-navy">{r.publicTitle}</h2><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-8 text-[#586e7a]">{r.publicBody}</p>{r.editorNote&&<div className="mt-5 rounded-lg bg-soft p-4 text-xs leading-7 text-[#41746c]">编辑说明：{r.editorNote}</div>}{r.sourceUrl&&<a className="mt-4 block break-all text-xs font-semibold text-brand" href={safeUrl(r.sourceUrl)} target="_blank" rel="noopener noreferrer">投稿所提供的公开来源 ↗</a>}<div className="mt-5 flex items-center gap-1 text-xs text-[#8a9aa0]"><CalendarDays size={13}/>{r.publishedAt?.toISOString().slice(0,10)} · 已审核公开，相关叙述仍需独立核对</div></article>)}</div>}</div>
}
